default: &default
  adapter: mysql2
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: <%= ENV["DEV_DB_NAME"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DB_NAME"] %>

production: &productioninfo
  adapter:  mysql2
  database: <%= ENV["PROD_DB_NAME"] %>
  username: <%= ENV["PROD_DB_USERNAME"] %>
  password: <%= ENV["PROD_DB_USERNAME"] %>
  host:     <%= ENV["PROD_DB_HOST"] %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  pool: 5